version: '2.1'
services:
  mysqldb:
    image: mysql
    container_name: mysqldb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - ./data/mysqldb:/mnt
  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
